### PR TITLE
Fix: arrow function scope strictness (take 2)

### LINKED ISSUE #49: ArrowFunctionExpression's scope is always strict scope
It seems to be deliberate that `eslint-scope` always sets `isStrict` to `true` for arrow function scopes. But this is not how it works in all the engines I could get my hands to.

I used assignment to an undeclared variable to check if the code is in strict mode:

With explicit strict mode, we get an error:
```bash
node -e '"use strict"; (() => { a = 5 })()'
# ReferenceError: a is not defined
```

Without `"use strict"` an error is not thrown, which means it's not in strict mode, but `eslint-scope` would treat the scope as strict anyway:
```bash
node -e '(() => { x = 1 })()'
```

I also checked with the spec's definition of strict mode code, and it seems that arrow functions should not get any special treatment (only classes should): https://www.ecma-international.org/ecma-262/#sec-strict-mode-code

https://github.com/eslint/eslint-scope/blob/3e69fdcf102082f3b3c419d0864d7ed90323f4ca/lib/scope.js#L52-L55

https://github.com/eslint/eslint-scope/blob/3e69fdcf102082f3b3c419d0864d7ed90323f4ca/tests/es6-arrow-function-expression.js#L55

### PR DESCRIPTION
**Pull request by futpib**
Fixes #49 

This has the original (broken) commit from #50 cherry-picked, and a separate a4ee79e commit fixing the `.length` error from #51.

I found linking (`npm link`) `eslint-scope` into `eslint` and running eslint's unit tests helpful, maybe this could be part of the `eslint-scope`'s CI checks?

### CODE REVIEW

File: lib/scope.js [hunk 1]
```diff
@@ -82,6 +77,11 @@ function isStrictScope(scope, block, isMethodDefinition, useDirective) {
         return false;
     }
 
+    // A function with non-block body, like `() => 1`
+    if (!body.body) {
```
Comment (mysticatea) [inline lib/scope.js]: I'd like to move this check into the `if` block about `scope.type === "function"` above. Because the type of `body` is unknown at this location.

Maybe:

```js
    if (scope.type === "function") {
        if (block.type === Syntax.ArrowFunctionExpression && block.body.type !== Syntax.BlockStatement) {
            return false;
        }
        //....
```

Comment (futpib) [reply lib/scope.js]: I applied this verbatim, eslint-scope and eslint tests still pass. :ok_hand:

**Comment by ilyavolodin** [comment]
Can this PR be merged at this point? Or do we need some more reviews?

**Comment by not-an-aardvark** [comment]
Seems mergeable to me. We should plan to do another `eslint-scope` release along with the next ESLint release.

**Comment by not-an-aardvark** [comment]
Thanks!
